### ISSUE TITLE
TDD or BDD?

### ISSUE THREAD

**Issue by mateusnroll** [go-ike/ike-base#2]
I remember in the old web-base days, me and @limazix had this argument about whether we should use BDD or TDD.

Before we decide, we should first know what we're talking about in depth. After doing some reading, I figured I don't know enough to make a decision yet. What I've found and read so far:

- http://joshldavis.com/2013/05/27/difference-between-tdd-and-bdd/
- https://www.toptal.com/freelance/your-boss-won-t-appreciate-tdd-try-bdd

So far, I'm convinced BDD is the best way forward. But maybe that's my designer bias talking louder, since it makes more sense to me to write BDD since they can be easily derived from a story's acceptance criteria.

I'm also assuming that we're doing either one or the other, since doing both might be to time-consuming. Do you think otherwise?

@go-ike/main Excited to hear your thoughts!

**Comment by lucasulcas** [comment]
BDD => Behavior Driven Development, at most cases this will test the application on a "high-level".

TDD => Test Driven Development it mostly implemented in libraries, it's mostly used to test unique functions , following the path of the [Single Responsibility Principle](https://blog.8thlight.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html) , where every function, ideally, do only one task.


This is my idea/thoughts behind the BDD and TDD, what do you guys think ?

@go-ike/main @mateusnroll

**Comment by lucasulcas** [comment]
@go-ike/main There is this awesome course : [Node.js Testing Strategies](https://app.pluralsight.com/library/courses/nodejs-testing-strategies/table-of-contents) at Pluralsight.

**Comment by mateusnroll** [comment]
@lucasulcas As far as I see it, they can be complementary but it will take too long to have both tests in place. It's possible in a consumer software to have both, but what's the gain?

If I understood correctly, you're saying that for consumer software BDD is the way, and TDD is more for libraries. Correct?

**Comment by mateusnroll** [comment]
Discussion closed 👍
